-- 0030 — MKB-10 spravochnigi. PLAN-180, S2.2.
--
-- Muammo: qidiruv endpointi (`/api/icd10`), indeks va interfeys joyida edi,
-- lekin `ICD10Code` jadvalida BOR-YO'G'I 1 TA QATOR bor edi. Ya'ni bu kod
-- bugi emas, ma'lumot bugi: qidiruv to'g'ri ishlab, har doim bo'sh natija
-- qaytarardi va qabulga tashxis umuman kiritib bo'lmasdi (audit B-02).
--
-- Bu yerda 345 ta kod — to'liq MKB-10 emas (unda 14 mingdan
-- ortiq kod bor, katta qismi statsionar va statistika uchun), balki ko'p
-- profilli AMBULATOR klinikada haqiqatan yoziladigan tashxislar.
--
-- Manba: backend/icd10Data.ts. Bu fayl QO'LDA TAHRIRLANMAYDI —
-- `npx tsx scripts/genIcd10Migration.ts` bilan qayta yasaladi.
-- Yangi kod kerak bo'lsa: manbaga qo'shiladi va YANGI migratsiya yasaladi.

-- Ruscha nom uchun ustun. Qidiruv ikkala tilda ham ishlashi kerak:
-- shifokor "gipert" yozsa ham, "гиперт" yozsa ham topsin.
ALTER TABLE "ICD10Code" ADD COLUMN "nameRu" TEXT;

-- `INSERT OR REPLACE` — migratsiya bir marta yuriladi, lekin bazada
-- allaqachon bitta qator bor va u shu ro'yxatga tushishi mumkin.
INSERT OR REPLACE INTO "ICD10Code" ("code", "name", "nameRu", "category") VALUES
  ('A02.0', 'Salmonellyoz enteriti', 'Сальмонеллёзный энтерит', 'Yuqumli kasalliklar'),
  ('A04.9', 'Bakterial ichak infeksiyasi, aniqlanmagan', 'Бактериальная кишечная инфекция неуточнённая', 'Yuqumli kasalliklar'),
  ('A08.4', 'Virusli ichak infeksiyasi, aniqlanmagan', 'Вирусная кишечная инфекция неуточнённая', 'Yuqumli kasalliklar'),
  ('A09', 'Yuqumli deb taxmin qilingan diareya va gastroenterit', 'Диарея и гастроэнтерит предположительно инфекционного происхождения', 'Yuqumli kasalliklar'),
  ('A15.0', 'O‘pka sili, bakteriologik tasdiqlangan', 'Туберкулёз лёгких, подтверждённый бактериологически', 'Yuqumli kasalliklar'),
  ('A16.2', 'O‘pka sili, tasdiqlanmagan', 'Туберкулёз лёгких без бактериологического подтверждения', 'Yuqumli kasalliklar'),
  ('A46', 'Roja (qizil shamol)', 'Рожа', 'Yuqumli kasalliklar'),
  ('A49.9', 'Bakterial infeksiya, aniqlanmagan', 'Бактериальная инфекция неуточнённая', 'Yuqumli kasalliklar'),
  ('B00.1', 'Gerpetik lab va yuz toshmasi', 'Герпетический везикулярный дерматит', 'Yuqumli kasalliklar'),
  ('B01.9', 'Suvchechak, asoratsiz', 'Ветряная оспа без осложнений', 'Yuqumli kasalliklar'),
  ('B02.9', 'O‘rab oluvchi temiratki, asoratsiz', 'Опоясывающий лишай без осложнений', 'Yuqumli kasalliklar'),
  ('B15.9', 'A gepatiti, komasiz', 'Гепатит A без печёночной комы', 'Yuqumli kasalliklar'),
  ('B16.9', 'O‘tkir B gepatiti', 'Острый гепатит B', 'Yuqumli kasalliklar'),
  ('B18.1', 'Surunkali B gepatiti', 'Хронический вирусный гепатит B', 'Yuqumli kasalliklar'),
  ('B18.2', 'Surunkali C gepatiti', 'Хронический вирусный гепатит C', 'Yuqumli kasalliklar'),
  ('B26.9', 'Tepki (parotit), asoratsiz', 'Эпидемический паротит без осложнений', 'Yuqumli kasalliklar'),
  ('B34.9', 'Virusli infeksiya, aniqlanmagan', 'Вирусная инфекция неуточнённая', 'Yuqumli kasalliklar'),
  ('B35.1', 'Tirnoq mikozi (onixomikoz)', 'Микоз ногтей', 'Yuqumli kasalliklar'),
  ('B35.3', 'Oyoq mikozi', 'Микоз стоп', 'Yuqumli kasalliklar'),
  ('B37.3', 'Vulva va vaginaning kandidozi', 'Кандидоз вульвы и вагины', 'Yuqumli kasalliklar'),
  ('B37.9', 'Kandidoz, aniqlanmagan', 'Кандидоз неуточнённый', 'Yuqumli kasalliklar'),
  ('B77.9', 'Askaridoz', 'Аскаридоз', 'Yuqumli kasalliklar'),
  ('B80', 'Enterobioz (gijja)', 'Энтеробиоз', 'Yuqumli kasalliklar'),
  ('B86', 'Qo‘tir', 'Чесотка', 'Yuqumli kasalliklar'),
  ('C50.9', 'Sut bezi xavfli o‘smasi', 'Злокачественное новообразование молочной железы', 'O''smalar'),
  ('C53.9', 'Bachadon bo‘yni xavfli o‘smasi', 'Злокачественное новообразование шейки матки', 'O''smalar'),
  ('C61', 'Prostata bezi xavfli o‘smasi', 'Злокачественное новообразование предстательной железы', 'O''smalar'),
  ('C73', 'Qalqonsimon bez xavfli o‘smasi', 'Злокачественное новообразование щитовидной железы', 'O''smalar'),
  ('D17.9', 'Lipoma', 'Липома', 'O''smalar'),
  ('D18.0', 'Gemangioma', 'Гемангиома', 'O''smalar'),
  ('D22.9', 'Melanoformali nevus (xol)', 'Меланоформный невус', 'O''smalar'),
  ('D24', 'Sut bezining xavfsiz o‘smasi', 'Доброкачественное новообразование молочной железы', 'O''smalar'),
  ('D25.9', 'Bachadon miomasi', 'Лейомиома матки', 'O''smalar'),
  ('D27', 'Tuxumdonning xavfsiz o‘smasi', 'Доброкачественное новообразование яичника', 'O''smalar'),
  ('D34', 'Qalqonsimon bezning xavfsiz o‘smasi', 'Доброкачественное новообразование щитовидной железы', 'O''smalar'),
  ('D36.9', 'Xavfsiz o‘sma, aniqlanmagan', 'Доброкачественное новообразование неуточнённой локализации', 'O''smalar'),
  ('D50.0', 'Surunkali qon yo‘qotishdan temir tanqisligi anemiyasi', 'Железодефицитная анемия вследствие хронической кровопотери', 'Qon kasalliklari'),
  ('D50.9', 'Temir tanqisligi anemiyasi', 'Железодефицитная анемия неуточнённая', 'Qon kasalliklari'),
  ('D51.9', 'B12-tanqisligi anemiyasi', 'B12-дефицитная анемия неуточнённая', 'Qon kasalliklari'),
  ('D52.9', 'Folat tanqisligi anemiyasi', 'Фолиеводефицитная анемия неуточнённая', 'Qon kasalliklari'),
  ('D64.9', 'Anemiya, aniqlanmagan', 'Анемия неуточнённая', 'Qon kasalliklari'),
  ('D68.9', 'Qon ivishining buzilishi', 'Нарушение свёртываемости крови неуточнённое', 'Qon kasalliklari'),
  ('D69.6', 'Trombotsitopeniya, aniqlanmagan', 'Тромбоцитопения неуточнённая', 'Qon kasalliklari'),
  ('E01.0', 'Yod tanqisligiga bog‘liq diffuz buqoq', 'Диффузный зоб, связанный с йодной недостаточностью', 'Endokrinologiya'),
  ('E03.9', 'Gipotireoz, aniqlanmagan', 'Гипотиреоз неуточнённый', 'Endokrinologiya'),
  ('E04.1', 'Bir tugunli buqoq', 'Нетоксический одноузловой зоб', 'Endokrinologiya'),
  ('E04.2', 'Ko‘p tugunli buqoq', 'Нетоксический многоузловой зоб', 'Endokrinologiya'),
  ('E05.9', 'Tireotoksikoz, aniqlanmagan', 'Тиреотоксикоз неуточнённый', 'Endokrinologiya'),
  ('E06.3', 'Autoimmun tireoidit', 'Аутоиммунный тиреоидит', 'Endokrinologiya'),
  ('E10.9', '1-tur qandli diabet, asoratsiz', 'Сахарный диабет 1 типа без осложнений', 'Endokrinologiya'),
  ('E11.9', '2-tur qandli diabet, asoratsiz', 'Сахарный диабет 2 типа без осложнений', 'Endokrinologiya'),
  ('E11.7', '2-tur qandli diabet, ko‘p asoratli', 'Сахарный диабет 2 типа с множественными осложнениями', 'Endokrinologiya'),
  ('E14.9', 'Qandli diabet, aniqlanmagan', 'Сахарный диабет неуточнённый', 'Endokrinologiya'),
  ('E16.2', 'Gipoglikemiya, aniqlanmagan', 'Гипогликемия неуточнённая', 'Endokrinologiya'),
  ('E28.2', 'Polikistoz tuxumdon sindromi', 'Синдром поликистозных яичников', 'Endokrinologiya'),
  ('E29.1', 'Moyak gipofunksiyasi', 'Гипофункция яичек', 'Endokrinologiya'),
  ('E55.9', 'D vitamini tanqisligi', 'Недостаточность витамина D неуточнённая', 'Endokrinologiya'),
  ('E61.1', 'Temir tanqisligi', 'Недостаточность железа', 'Endokrinologiya'),
  ('E66.0', 'Ortiqcha ovqatlanishdan semizlik', 'Ожирение, обусловленное избыточным поступлением энергии', 'Endokrinologiya'),
  ('E66.9', 'Semizlik, aniqlanmagan', 'Ожирение неуточнённое', 'Endokrinologiya'),
  ('E78.0', 'Sof giperxolesterinemiya', 'Чистая гиперхолестеринемия', 'Endokrinologiya'),
  ('E78.5', 'Giperlipidemiya, aniqlanmagan', 'Гиперлипидемия неуточнённая', 'Endokrinologiya'),
  ('E86', 'Suyuqlik hajmining kamayishi (degidratatsiya)', 'Уменьшение объёма жидкости', 'Endokrinologiya'),
  ('E87.6', 'Gipokaliemiya', 'Гипокалиемия', 'Endokrinologiya'),
  ('F32.9', 'Depressiv epizod, aniqlanmagan', 'Депрессивный эпизод неуточнённый', 'Ruhiy salomatlik'),
  ('F41.0', 'Vahima (panik) buzilishi', 'Паническое расстройство', 'Ruhiy salomatlik'),
  ('F41.1', 'Generallashgan xavotir buzilishi', 'Генерализованное тревожное расстройство', 'Ruhiy salomatlik'),
  ('F41.2', 'Aralash xavotir va depressiv buzilish', 'Смешанное тревожное и депрессивное расстройство', 'Ruhiy salomatlik'),
  ('F43.2', 'Adaptatsiya buzilishi', 'Расстройство приспособительных реакций', 'Ruhiy salomatlik'),
  ('F45.3', 'Somatoform vegetativ disfunksiya', 'Соматоформная дисфункция вегетативной нервной системы', 'Ruhiy salomatlik'),
  ('F48.0', 'Nevrasteniya', 'Неврастения', 'Ruhiy salomatlik'),
  ('F51.0', 'Organik bo‘lmagan uyqusizlik', 'Бессонница неорганической природы', 'Ruhiy salomatlik'),
  ('F90.0', 'Diqqat yetishmovchiligi va giperaktivlik', 'Нарушение активности и внимания', 'Ruhiy salomatlik'),
  ('G40.9', 'Epilepsiya, aniqlanmagan', 'Эпилепсия неуточнённая', 'Nevrologiya'),
  ('G43.9', 'Migren, aniqlanmagan', 'Мигрень неуточнённая', 'Nevrologiya'),
  ('G44.2', 'Zo‘riqish bosh og‘rig‘i', 'Головная боль напряжённого типа', 'Nevrologiya'),
  ('G45.9', 'O‘tkinchi ishemik xuruj', 'Транзиторная церебральная ишемическая атака', 'Nevrologiya'),
  ('G47.0', 'Uyquga ketish va uyquni saqlashning buzilishi', 'Нарушения засыпания и поддержания сна', 'Nevrologiya'),
  ('G50.0', 'Uch shoxli nerv nevralgiyasi', 'Невралгия тройничного нерва', 'Nevrologiya'),
  ('G51.0', 'Yuz nervi falaji (Bell)', 'Паралич Белла', 'Nevrologiya'),
  ('G54.1', 'Bel-dumg‘aza chigalining shikastlanishi', 'Поражения пояснично-крестцового сплетения', 'Nevrologiya'),
  ('G56.0', 'Bilak kanali sindromi', 'Синдром запястного канала', 'Nevrologiya'),
  ('G62.9', 'Polinevropatiya, aniqlanmagan', 'Полиневропатия неуточнённая', 'Nevrologiya'),
  ('G90.9', 'Vegetativ nerv sistemasi buzilishi', 'Расстройство вегетативной нервной системы неуточнённое', 'Nevrologiya'),
  ('G93.3', 'Charchoq sindromi (virusdan keyingi)', 'Синдром утомляемости после перенесённой вирусной болезни', 'Nevrologiya'),
  ('H00.0', 'Gordeolum (arpacha)', 'Гордеолум (ячмень)', 'Oftalmologiya'),
  ('H10.9', 'Konyunktivit, aniqlanmagan', 'Конъюнктивит неуточнённый', 'Oftalmologiya'),
  ('H16.9', 'Keratit, aniqlanmagan', 'Кератит неуточнённый', 'Oftalmologiya'),
  ('H25.9', 'Keksalik kataraktasi', 'Старческая катаракта неуточнённая', 'Oftalmologiya'),
  ('H40.9', 'Glaukoma, aniqlanmagan', 'Глаукома неуточнённая', 'Oftalmologiya'),
  ('H52.0', 'Uzoqni ko‘rish (gipermetropiya)', 'Гиперметропия', 'Oftalmologiya'),
  ('H52.1', 'Yaqinni ko‘rish (miopiya)', 'Миопия', 'Oftalmologiya'),
  ('H52.2', 'Astigmatizm', 'Астигматизм', 'Oftalmologiya'),
  ('H52.4', 'Presbiopiya', 'Пресбиопия', 'Oftalmologiya'),
  ('H57.1', 'Ko‘z og‘rig‘i', 'Глазная боль', 'Oftalmologiya'),
  ('H60.9', 'Tashqi otit, aniqlanmagan', 'Наружный отит неуточнённый', 'LOR'),
  ('H65.9', 'Yiringsiz o‘rta otit', 'Негнойный средний отит неуточнённый', 'LOR'),
  ('H66.0', 'O‘tkir yiringli o‘rta otit', 'Острый гнойный средний отит', 'LOR'),
  ('H66.9', 'O‘rta otit, aniqlanmagan', 'Средний отит неуточнённый', 'LOR'),
  ('H81.1', 'Yaxshi sifatli pozitsion vertigo', 'Доброкачественное пароксизмальное головокружение', 'LOR'),
  ('H81.3', 'Boshqa periferik vertigo', 'Другие периферические головокружения', 'LOR'),
  ('H90.3', 'Ikki tomonlama neyrosensor eshitish pasayishi', 'Нейросенсорная потеря слуха двусторонняя', 'LOR'),
  ('H92.0', 'Quloq og‘rig‘i (otalgiya)', 'Оталгия', 'LOR'),
  ('H93.1', 'Quloqda shovqin (tinnitus)', 'Шум в ушах', 'LOR'),
  ('I10', 'Essensial (birlamchi) arterial gipertenziya', 'Эссенциальная (первичная) гипертензия', 'Kardiologiya'),
  ('I11.9', 'Gipertoniya kasalligi, yurak shikastlanishi bilan', 'Гипертензивная болезнь сердца без сердечной недостаточности', 'Kardiologiya'),
  ('I15.9', 'Ikkilamchi gipertenziya', 'Вторичная гипертензия неуточнённая', 'Kardiologiya'),
  ('I20.0', 'Beqaror stenokardiya', 'Нестабильная стенокардия', 'Kardiologiya'),
  ('I20.8', 'Stenokardiyaning boshqa shakllari', 'Другие формы стенокардии', 'Kardiologiya'),
  ('I21.9', 'O‘tkir miokard infarkti', 'Острый инфаркт миокарда неуточнённый', 'Kardiologiya'),
  ('I25.1', 'Aterosklerotik yurak kasalligi', 'Атеросклеротическая болезнь сердца', 'Kardiologiya'),
  ('I25.9', 'Surunkali ishemik yurak kasalligi', 'Хроническая ишемическая болезнь сердца неуточнённая', 'Kardiologiya'),
  ('I34.0', 'Mitral klapan yetishmovchiligi', 'Митральная недостаточность', 'Kardiologiya'),
  ('I44.0', 'Birinchi darajali atrioventrikulyar blokada', 'Предсердно-желудочковая блокада первой степени', 'Kardiologiya'),
  ('I47.1', 'Supraventrikulyar taxikardiya', 'Наджелудочковая тахикардия', 'Kardiologiya'),
  ('I48', 'Bo‘lmachalar fibrillyatsiyasi va titrashi', 'Фибрилляция и трепетание предсердий', 'Kardiologiya'),
  ('I49.3', 'Qorincha ekstrasistoliyasi', 'Преждевременная деполяризация желудочков', 'Kardiologiya'),
  ('I49.9', 'Yurak ritmi buzilishi, aniqlanmagan', 'Нарушение сердечного ритма неуточнённое', 'Kardiologiya'),
  ('I50.0', 'Dimlanish yurak yetishmovchiligi', 'Застойная сердечная недостаточность', 'Kardiologiya'),
  ('I50.9', 'Yurak yetishmovchiligi, aniqlanmagan', 'Сердечная недостаточность неуточнённая', 'Kardiologiya'),
  ('I63.9', 'Miya infarkti, aniqlanmagan', 'Инфаркт мозга неуточнённый', 'Kardiologiya'),
  ('I67.8', 'Miya qon aylanishining surunkali yetishmovchiligi', 'Другие уточнённые поражения сосудов мозга', 'Kardiologiya'),
  ('I70.2', 'Oyoq arteriyalari aterosklerozi', 'Атеросклероз артерий конечностей', 'Kardiologiya'),
  ('I73.9', 'Periferik qon tomir kasalligi', 'Болезнь периферических сосудов неуточнённая', 'Kardiologiya'),
  ('I80.2', 'Oyoq chuqur venalari flebiti va tromboflebiti', 'Флебит и тромбофлебит глубоких сосудов конечностей', 'Kardiologiya'),
  ('I83.9', 'Oyoq varikoz kengayishi, asoratsiz', 'Варикозное расширение вен нижних конечностей без язвы', 'Kardiologiya'),
  ('I84.1', 'Ichki bavosil, asorat bilan', 'Внутренний геморрой с осложнением', 'Kardiologiya'),
  ('I84.9', 'Bavosil, aniqlanmagan', 'Геморрой неуточнённый', 'Kardiologiya'),
  ('I95.9', 'Gipotenziya, aniqlanmagan', 'Гипотензия неуточнённая', 'Kardiologiya'),
  ('J00', 'O‘tkir nazofaringit (tumov)', 'Острый назофарингит (насморк)', 'Pulmonologiya'),
  ('J01.0', 'O‘tkir gaymorit', 'Острый верхнечелюстной синусит', 'Pulmonologiya'),
  ('J01.9', 'O‘tkir sinusit, aniqlanmagan', 'Острый синусит неуточнённый', 'Pulmonologiya'),
  ('J02.9', 'O‘tkir faringit', 'Острый фарингит неуточнённый', 'Pulmonologiya'),
  ('J03.9', 'O‘tkir tonzillit (angina)', 'Острый тонзиллит неуточнённый', 'Pulmonologiya'),
  ('J04.0', 'O‘tkir laringit', 'Острый ларингит', 'Pulmonologiya'),
  ('J06.9', 'O‘tkir yuqori nafas yo‘llari infeksiyasi (ORVI)', 'Острая инфекция верхних дыхательных путей неуточнённая', 'Pulmonologiya'),
  ('J11.1', 'Grip, virus aniqlanmagan', 'Грипп, вирус не идентифицирован', 'Pulmonologiya'),
  ('J15.9', 'Bakterial pnevmoniya, aniqlanmagan', 'Бактериальная пневмония неуточнённая', 'Pulmonologiya'),
  ('J18.9', 'Pnevmoniya, aniqlanmagan', 'Пневмония неуточнённая', 'Pulmonologiya'),
  ('J20.9', 'O‘tkir bronxit', 'Острый бронхит неуточнённый', 'Pulmonologiya'),
  ('J30.1', 'Gulchang allergik rinit', 'Аллергический ринит, вызванный пыльцой', 'Pulmonologiya'),
  ('J30.4', 'Allergik rinit, aniqlanmagan', 'Аллергический ринит неуточнённый', 'Pulmonologiya'),
  ('J31.0', 'Surunkali rinit', 'Хронический ринит', 'Pulmonologiya'),
  ('J32.9', 'Surunkali sinusit', 'Хронический синусит неуточнённый', 'Pulmonologiya'),
  ('J34.2', 'Burun to‘sig‘ining qiyshayishi', 'Смещённая носовая перегородка', 'Pulmonologiya'),
  ('J35.0', 'Surunkali tonzillit', 'Хронический тонзиллит', 'Pulmonologiya'),
  ('J35.2', 'Adenoidlar kattalashishi', 'Гипертрофия аденоидов', 'Pulmonologiya'),
  ('J40', 'Bronxit, o‘tkir yoki surunkaligi aniqlanmagan', 'Бронхит, не уточнённый как острый или хронический', 'Pulmonologiya'),
  ('J42', 'Surunkali bronxit', 'Хронический бронхит неуточнённый', 'Pulmonologiya'),
  ('J44.9', 'Surunkali obstruktiv o‘pka kasalligi', 'Хроническая обструктивная лёгочная болезнь неуточнённая', 'Pulmonologiya'),
  ('J45.9', 'Bronxial astma, aniqlanmagan', 'Астма неуточнённая', 'Pulmonologiya'),
  ('J98.9', 'Nafas buzilishi, aniqlanmagan', 'Респираторное нарушение неуточнённое', 'Pulmonologiya'),
  ('K02.9', 'Tish kariyesi', 'Кариес зубов неуточнённый', 'Gastroenterologiya'),
  ('K05.1', 'Surunkali gingivit', 'Хронический гингивит', 'Gastroenterologiya'),
  ('K12.0', 'Og‘izdagi aftalar', 'Рецидивирующие афты полости рта', 'Gastroenterologiya'),
  ('K21.0', 'Gastroezofageal reflyuks, ezofagit bilan', 'Гастроэзофагеальный рефлюкс с эзофагитом', 'Gastroenterologiya'),
  ('K21.9', 'Gastroezofageal reflyuks, ezofagitsiz', 'Гастроэзофагеальный рефлюкс без эзофагита', 'Gastroenterologiya'),
  ('K25.9', 'Oshqozon yarasi', 'Язва желудка неуточнённая', 'Gastroenterologiya'),
  ('K26.9', 'O‘n ikki barmoq ichak yarasi', 'Язва двенадцатиперстной кишки неуточнённая', 'Gastroenterologiya'),
  ('K29.1', 'O‘tkir gastrit', 'Другие острые гастриты', 'Gastroenterologiya'),
  ('K29.5', 'Surunkali gastrit, aniqlanmagan', 'Хронический гастрит неуточнённый', 'Gastroenterologiya'),
  ('K29.7', 'Gastrit, aniqlanmagan', 'Гастрит неуточнённый', 'Gastroenterologiya'),
  ('K30', 'Funksional dispepsiya', 'Функциональная диспепсия', 'Gastroenterologiya'),
  ('K35.8', 'O‘tkir appenditsit', 'Острый аппендицит неуточнённый', 'Gastroenterologiya'),
  ('K40.9', 'Bir tomonlama chov churrasi', 'Односторонняя паховая грыжа без непроходимости', 'Gastroenterologiya'),
  ('K42.9', 'Kindik churrasi', 'Пупочная грыжа без непроходимости', 'Gastroenterologiya'),
  ('K52.9', 'Yuqumsiz gastroenterit va kolit', 'Неинфекционный гастроэнтерит и колит неуточнённый', 'Gastroenterologiya'),
  ('K57.3', 'Yo‘g‘on ichak divertikulyoz kasalligi', 'Дивертикулярная болезнь толстой кишки', 'Gastroenterologiya'),
  ('K58.9', 'Ta’sirchan ichak sindromi', 'Синдром раздражённого кишечника без диареи', 'Gastroenterologiya'),
  ('K59.0', 'Qabziyat', 'Запор', 'Gastroenterologiya'),
  ('K60.2', 'Anal yoriq, aniqlanmagan', 'Анальная трещина неуточнённая', 'Gastroenterologiya'),
  ('K73.9', 'Surunkali gepatit, aniqlanmagan', 'Хронический гепатит неуточнённый', 'Gastroenterologiya'),
  ('K76.0', 'Jigarning yog‘li distrofiyasi', 'Жировая дегенерация печени', 'Gastroenterologiya'),
  ('K80.2', 'O‘t pufagi toshi, xoletsistitsiz', 'Камни жёлчного пузыря без холецистита', 'Gastroenterologiya'),
  ('K81.1', 'Surunkali xoletsistit', 'Хронический холецистит', 'Gastroenterologiya'),
  ('K82.8', 'O‘t pufagining boshqa kasalliklari', 'Другие уточнённые болезни жёлчного пузыря', 'Gastroenterologiya'),
  ('K85.9', 'O‘tkir pankreatit', 'Острый панкреатит неуточнённый', 'Gastroenterologiya'),
  ('K86.1', 'Surunkali pankreatit', 'Другие хронические панкреатиты', 'Gastroenterologiya'),
  ('L01.0', 'Impetigo', 'Импетиго', 'Dermatologiya'),
  ('L02.9', 'Teri absessi, chipqon', 'Абсцесс кожи, фурункул и карбункул неуточнённой локализации', 'Dermatologiya'),
  ('L03.9', 'Flegmona, aniqlanmagan', 'Флегмона неуточнённая', 'Dermatologiya'),
  ('L20.9', 'Atopik dermatit', 'Атопический дерматит неуточнённый', 'Dermatologiya'),
  ('L21.9', 'Seboreyali dermatit', 'Себорейный дерматит неуточнённый', 'Dermatologiya'),
  ('L23.9', 'Allergik kontakt dermatit', 'Аллергический контактный дерматит неуточнённый', 'Dermatologiya'),
  ('L25.9', 'Kontakt dermatit, aniqlanmagan', 'Контактный дерматит неуточнённый', 'Dermatologiya'),
  ('L29.9', 'Qichishish, aniqlanmagan', 'Зуд неуточнённый', 'Dermatologiya'),
  ('L30.9', 'Dermatit, aniqlanmagan', 'Дерматит неуточнённый', 'Dermatologiya'),
  ('L40.9', 'Psoriaz, aniqlanmagan', 'Псориаз неуточнённый', 'Dermatologiya'),
  ('L50.9', 'Eshakem (krapivnitsa)', 'Крапивница неуточнённая', 'Dermatologiya'),
  ('L60.0', 'Tirnoqning botib o‘sishi', 'Вросший ноготь', 'Dermatologiya'),
  ('L63.9', 'Uyalab soch to‘kilishi', 'Гнёздная алопеция неуточнённая', 'Dermatologiya'),
  ('L64.9', 'Androgen alopetsiya', 'Андрогенная алопеция неуточнённая', 'Dermatologiya'),
  ('L70.0', 'Oddiy husnbuzar (akne)', 'Угри обыкновенные', 'Dermatologiya'),
  ('L71.9', 'Rozatsea', 'Розацеа неуточнённая', 'Dermatologiya'),
  ('L81.4', 'Melanin giperpigmentatsiyasi', 'Другая меланиновая гиперпигментация', 'Dermatologiya'),
  ('L84', 'Qadoq va suyaklar', 'Мозоли и омозолелости', 'Dermatologiya'),
  ('L98.9', 'Teri kasalligi, aniqlanmagan', 'Поражение кожи неуточнённое', 'Dermatologiya'),
  ('M05.9', 'Seropozitiv revmatoid artrit', 'Серопозитивный ревматоидный артрит неуточнённый', 'Travmatologiya va ortopediya'),
  ('M10.9', 'Podagra, aniqlanmagan', 'Подагра неуточнённая', 'Travmatologiya va ortopediya'),
  ('M13.9', 'Artrit, aniqlanmagan', 'Артрит неуточнённый', 'Travmatologiya va ortopediya'),
  ('M15.9', 'Poliartroz, aniqlanmagan', 'Полиартроз неуточнённый', 'Travmatologiya va ortopediya'),
  ('M16.9', 'Chanoq-son bo‘g‘imi artrozi', 'Коксартроз неуточнённый', 'Travmatologiya va ortopediya'),
  ('M17.9', 'Tizza bo‘g‘imi artrozi', 'Гонартроз неуточнённый', 'Travmatologiya va ortopediya'),
  ('M19.9', 'Artroz, aniqlanmagan', 'Артроз неуточнённый', 'Travmatologiya va ortopediya'),
  ('M25.5', 'Bo‘g‘im og‘rig‘i (artralgiya)', 'Боль в суставе', 'Travmatologiya va ortopediya'),
  ('M42.1', 'Kattalarda osteoxondroz', 'Остеохондроз позвоночника у взрослых', 'Travmatologiya va ortopediya'),
  ('M47.9', 'Spondilyoz, aniqlanmagan', 'Спондилёз неуточнённый', 'Travmatologiya va ortopediya'),
  ('M51.1', 'Bel disklari radikulopatiya bilan', 'Поражения межпозвоночных дисков с радикулопатией', 'Travmatologiya va ortopediya'),
  ('M53.1', 'Servikokranial sindrom', 'Шейно-черепной синдром', 'Travmatologiya va ortopediya'),
  ('M54.1', 'Radikulopatiya', 'Радикулопатия', 'Travmatologiya va ortopediya'),
  ('M54.2', 'Bo‘yin og‘rig‘i (servikalgiya)', 'Цервикалгия', 'Travmatologiya va ortopediya'),
  ('M54.4', 'Bel-dumg‘aza og‘rig‘i (lyumboishialgiya)', 'Люмбаго с ишиасом', 'Travmatologiya va ortopediya'),
  ('M54.5', 'Bel og‘rig‘i', 'Боль внизу спины', 'Travmatologiya va ortopediya'),
  ('M54.9', 'Dorsalgiya, aniqlanmagan', 'Дорсалгия неуточнённая', 'Travmatologiya va ortopediya'),
  ('M65.9', 'Sinovit va tenosinovit', 'Синовит и теносиновит неуточнённый', 'Travmatologiya va ortopediya'),
  ('M75.0', 'Yelka adgeziv kapsuliti', 'Адгезивный капсулит плеча', 'Travmatologiya va ortopediya'),
  ('M77.1', 'Lateral epikondilit (tennischi tirsagi)', 'Латеральный эпикондилит', 'Travmatologiya va ortopediya'),
  ('M79.1', 'Mialgiya', 'Миалгия', 'Travmatologiya va ortopediya'),
  ('M79.6', 'Oyoq-qo‘lda og‘riq', 'Боль в конечности', 'Travmatologiya va ortopediya'),
  ('M81.9', 'Osteoporoz, aniqlanmagan', 'Остеопороз неуточнённый', 'Travmatologiya va ortopediya'),
  ('M99.1', 'Umurtqa segmentar disfunksiyasi', 'Подвывих (сегментарное нарушение)', 'Travmatologiya va ortopediya'),
  ('N04.9', 'Nefrotik sindrom', 'Нефротический синдром неуточнённый', 'Urologiya va nefrologiya'),
  ('N10', 'O‘tkir tubulointerstitsial nefrit (pielonefrit)', 'Острый тубулоинтерстициальный нефрит', 'Urologiya va nefrologiya'),
  ('N11.9', 'Surunkali pielonefrit', 'Хронический тубулоинтерстициальный нефрит неуточнённый', 'Urologiya va nefrologiya'),
  ('N18.9', 'Surunkali buyrak kasalligi', 'Хроническая болезнь почки неуточнённая', 'Urologiya va nefrologiya'),
  ('N20.0', 'Buyrak toshi', 'Камни почки', 'Urologiya va nefrologiya'),
  ('N20.1', 'Siydik yo‘li toshi', 'Камни мочеточника', 'Urologiya va nefrologiya'),
  ('N23', 'Buyrak sanchig‘i, aniqlanmagan', 'Почечная колика неуточнённая', 'Urologiya va nefrologiya'),
  ('N30.0', 'O‘tkir sistit', 'Острый цистит', 'Urologiya va nefrologiya'),
  ('N30.9', 'Sistit, aniqlanmagan', 'Цистит неуточнённый', 'Urologiya va nefrologiya'),
  ('N39.0', 'Siydik yo‘llari infeksiyasi', 'Инфекция мочевыводящих путей без установленной локализации', 'Urologiya va nefrologiya'),
  ('N40', 'Prostata bezining giperplaziyasi', 'Гиперплазия предстательной железы', 'Urologiya va nefrologiya'),
  ('N41.0', 'O‘tkir prostatit', 'Острый простатит', 'Urologiya va nefrologiya'),
  ('N41.1', 'Surunkali prostatit', 'Хронический простатит', 'Urologiya va nefrologiya'),
  ('N43.3', 'Gidrotsele', 'Гидроцеле неуточнённое', 'Urologiya va nefrologiya'),
  ('N45.9', 'Orxit va epididimit', 'Орхит и эпидидимит', 'Urologiya va nefrologiya'),
  ('N47', 'Ortiqcha va tor qulfoq (fimoz)', 'Избыточная крайняя плоть, фимоз и парафимоз', 'Urologiya va nefrologiya'),
  ('N48.4', 'Erektil disfunksiya', 'Импотенция органического происхождения', 'Urologiya va nefrologiya'),
  ('N50.8', 'Erkak jinsiy a’zolarining boshqa kasalliklari', 'Другие уточнённые болезни мужских половых органов', 'Urologiya va nefrologiya'),
  ('N60.1', 'Diffuz kistoz mastopatiya', 'Диффузная кистозная мастопатия', 'Ginekologiya'),
  ('N61', 'Mastit', 'Воспалительные болезни молочной железы', 'Ginekologiya'),
  ('N63', 'Sut bezidagi tugun, aniqlanmagan', 'Образование в молочной железе неуточнённое', 'Ginekologiya'),
  ('N70.9', 'Salpingit va ooforit', 'Сальпингит и оофорит неуточнённые', 'Ginekologiya'),
  ('N71.9', 'Bachadonning yallig‘lanish kasalligi', 'Воспалительная болезнь матки неуточнённая', 'Ginekologiya'),
  ('N72', 'Bachadon bo‘yni yallig‘lanishi (servitsit)', 'Воспалительная болезнь шейки матки', 'Ginekologiya'),
  ('N73.9', 'Kichik chanoq yallig‘lanish kasalligi', 'Воспалительная болезнь женских тазовых органов неуточнённая', 'Ginekologiya'),
  ('N76.0', 'O‘tkir vaginit', 'Острый вагинит', 'Ginekologiya'),
  ('N76.1', 'Surunkali vaginit', 'Подострый и хронический вагинит', 'Ginekologiya'),
  ('N80.9', 'Endometrioz, aniqlanmagan', 'Эндометриоз неуточнённый', 'Ginekologiya'),
  ('N83.2', 'Tuxumdon kistasi', 'Другие и неуточнённые кисты яичника', 'Ginekologiya'),
  ('N84.1', 'Bachadon bo‘yni polipi', 'Полип шейки матки', 'Ginekologiya'),
  ('N85.0', 'Endometriyning bezli giperplaziyasi', 'Железистая гиперплазия эндометрия', 'Ginekologiya'),
  ('N86', 'Bachadon bo‘yni eroziyasi va ektropioni', 'Эрозия и эктропион шейки матки', 'Ginekologiya'),
  ('N87.9', 'Bachadon bo‘yni displaziyasi', 'Дисплазия шейки матки неуточнённая', 'Ginekologiya'),
  ('N91.2', 'Amenoreya, aniqlanmagan', 'Аменорея неуточнённая', 'Ginekologiya'),
  ('N92.0', 'Ko‘p va tez-tez hayz ko‘rish', 'Обильные и частые менструации при регулярном цикле', 'Ginekologiya'),
  ('N92.6', 'Tartibsiz hayz, aniqlanmagan', 'Нерегулярные менструации неуточнённые', 'Ginekologiya'),
  ('N94.6', 'Dismenoreya, aniqlanmagan', 'Дисменорея неуточнённая', 'Ginekologiya'),
  ('N95.1', 'Klimakterik holat', 'Менопаузное и климактерическое состояние у женщин', 'Ginekologiya'),
  ('N97.9', 'Ayol bepushtligi, aniqlanmagan', 'Женское бесплодие неуточнённое', 'Ginekologiya'),
  ('O00.1', 'Naycha homiladorligi', 'Трубная беременность', 'Homiladorlik va tug‘ruq'),
  ('O02.1', 'To‘xtab qolgan homiladorlik', 'Несостоявшийся выкидыш', 'Homiladorlik va tug‘ruq'),
  ('O03.9', 'O‘z-o‘zidan tushish', 'Самопроизвольный аборт неуточнённый', 'Homiladorlik va tug‘ruq'),
  ('O20.0', 'Tushish xavfi', 'Угрожающий аборт', 'Homiladorlik va tug‘ruq'),
  ('O21.0', 'Homiladorlarda yengil qusish', 'Рвота беременных лёгкая', 'Homiladorlik va tug‘ruq'),
  ('O23.4', 'Homiladorlikda siydik yo‘llari infeksiyasi', 'Инфекция мочевых путей при беременности неуточнённая', 'Homiladorlik va tug‘ruq'),
  ('O24.4', 'Homiladorlik diabeti', 'Сахарный диабет, возникший во время беременности', 'Homiladorlik va tug‘ruq'),
  ('O26.8', 'Homiladorlikning boshqa holatlari', 'Другие уточнённые состояния, связанные с беременностью', 'Homiladorlik va tug‘ruq'),
  ('O47.9', 'Soxta tug‘ruq faoliyati', 'Ложные схватки неуточнённые', 'Homiladorlik va tug‘ruq'),
  ('O80', 'Bir homilali normal tug‘ruq', 'Роды одноплодные, самопроизвольное родоразрешение', 'Homiladorlik va tug‘ruq'),
  ('O99.0', 'Homiladorlikni asoratlantiruvchi anemiya', 'Анемия, осложняющая беременность', 'Homiladorlik va tug‘ruq'),
  ('Z34.9', 'Normal homiladorlik kuzatuvi', 'Наблюдение за течением нормальной беременности', 'Homiladorlik va tug‘ruq'),
  ('Z35.9', 'Yuqori xavfli homiladorlik kuzatuvi', 'Наблюдение за беременностью высокого риска', 'Homiladorlik va tug‘ruq'),
  ('P07.3', 'Muddatidan oldin tug‘ilgan chaqaloq', 'Другие случаи недоношенности', 'Pediatriya'),
  ('P59.9', 'Yangi tug‘ilganlar sariqligi', 'Неонатальная желтуха неуточнённая', 'Pediatriya'),
  ('Q21.1', 'Bo‘lmachalararo to‘siq nuqsoni', 'Дефект предсердной перегородки', 'Pediatriya'),
  ('Q53.9', 'Moyak tushmasligi (kriptorxizm)', 'Неуточнённое неопущение яичка', 'Pediatriya'),
  ('Q65.9', 'Chanoq-son bo‘g‘imi tug‘ma deformatsiyasi', 'Врождённая деформация бедра неуточнённая', 'Pediatriya'),
  ('Q66.0', 'Tovon-oyoq varus deformatsiyasi', 'Конско-варусная косолапость', 'Pediatriya'),
  ('R62.8', 'Jismoniy rivojlanishdan orqada qolish', 'Другие виды задержки развития', 'Pediatriya'),
  ('Z00.1', 'Bolaning profilaktik ko‘rigi', 'Обычный медицинский осмотр ребёнка', 'Pediatriya'),
  ('Z23', 'Emlash uchun murojaat', 'Необходимость иммунизации', 'Pediatriya'),
  ('Z27.9', 'Kombinatsiyalangan emlash', 'Необходимость комбинированной иммунизации', 'Pediatriya'),
  ('R00.0', 'Taxikardiya, aniqlanmagan', 'Тахикардия неуточнённая', 'Alomatlar va noaniq holatlar'),
  ('R00.1', 'Bradikardiya, aniqlanmagan', 'Брадикардия неуточнённая', 'Alomatlar va noaniq holatlar'),
  ('R05', 'Yo‘tal', 'Кашель', 'Alomatlar va noaniq holatlar'),
  ('R06.0', 'Hansirash', 'Одышка', 'Alomatlar va noaniq holatlar'),
  ('R07.4', 'Ko‘krak qafasidagi og‘riq', 'Боль в груди неуточнённая', 'Alomatlar va noaniq holatlar'),
  ('R10.1', 'Qorinning yuqori qismidagi og‘riq', 'Боль, локализованная в верхней части живота', 'Alomatlar va noaniq holatlar'),
  ('R10.4', 'Qorin og‘rig‘i, aniqlanmagan', 'Другие и неуточнённые боли в области живота', 'Alomatlar va noaniq holatlar'),
  ('R11', 'Ko‘ngil aynishi va qusish', 'Тошнота и рвота', 'Alomatlar va noaniq holatlar'),
  ('R14', 'Meteorizm', 'Метеоризм и родственные состояния', 'Alomatlar va noaniq holatlar'),
  ('R19.7', 'Diareya, aniqlanmagan', 'Диарея неуточнённая', 'Alomatlar va noaniq holatlar'),
  ('R30.0', 'Siyishda og‘riq (dizuriya)', 'Дизурия', 'Alomatlar va noaniq holatlar'),
  ('R31', 'Gematuriya, aniqlanmagan', 'Неспецифическая гематурия', 'Alomatlar va noaniq holatlar'),
  ('R35', 'Poliuriya', 'Полиурия', 'Alomatlar va noaniq holatlar'),
  ('R42', 'Bosh aylanishi', 'Головокружение и нарушение устойчивости', 'Alomatlar va noaniq holatlar'),
  ('R50.9', 'Isitma, aniqlanmagan', 'Лихорадка неуточнённая', 'Alomatlar va noaniq holatlar'),
  ('R51', 'Bosh og‘rig‘i', 'Головная боль', 'Alomatlar va noaniq holatlar'),
  ('R53', 'Holsizlik va charchoq', 'Недомогание и утомляемость', 'Alomatlar va noaniq holatlar'),
  ('R55', 'Hushdan ketish (sinkope)', 'Обморок и коллапс', 'Alomatlar va noaniq holatlar'),
  ('R60.0', 'Mahalliy shish', 'Локализованный отёк', 'Alomatlar va noaniq holatlar'),
  ('R63.0', 'Ishtaha yo‘qolishi', 'Анорексия', 'Alomatlar va noaniq holatlar'),
  ('R63.5', 'Ortiqcha vazn ortishi', 'Ненормальная прибавка массы тела', 'Alomatlar va noaniq holatlar'),
  ('R73.9', 'Giperglikemiya, aniqlanmagan', 'Гипергликемия неуточнённая', 'Alomatlar va noaniq holatlar'),
  ('R79.8', 'Qon biokimyosidagi boshqa o‘zgarishlar', 'Другие уточнённые отклонения биохимии крови', 'Alomatlar va noaniq holatlar'),
  ('R94.3', 'EKG dagi o‘zgarishlar', 'Отклонения от нормы, выявленные при ЭКГ', 'Alomatlar va noaniq holatlar'),
  ('S00.9', 'Bosh yuzasining shikastlanishi', 'Поверхностная травма головы неуточнённая', 'Jarohatlar va zaharlanishlar'),
  ('S06.0', 'Miya chayqalishi', 'Сотрясение головного мозга', 'Jarohatlar va zaharlanishlar'),
  ('S13.4', 'Bo‘yin umurtqasi cho‘zilishi', 'Растяжение связок шейного отдела позвоночника', 'Jarohatlar va zaharlanishlar'),
  ('S22.3', 'Qovurg‘a sinishi', 'Перелом ребра', 'Jarohatlar va zaharlanishlar'),
  ('S42.3', 'Yelka suyagi tanasining sinishi', 'Перелом тела плечевой кости', 'Jarohatlar va zaharlanishlar'),
  ('S52.5', 'Bilak suyagi pastki uchining sinishi', 'Перелом нижнего конца лучевой кости', 'Jarohatlar va zaharlanishlar'),
  ('S61.9', 'Bilak va qo‘l ochiq yarasi', 'Открытая рана неуточнённой части запястья и кисти', 'Jarohatlar va zaharlanishlar'),
  ('S72.0', 'Son suyagi bo‘yni sinishi', 'Перелом шейки бедра', 'Jarohatlar va zaharlanishlar'),
  ('S82.6', 'Tashqi to‘piq sinishi', 'Перелом наружной лодыжки', 'Jarohatlar va zaharlanishlar'),
  ('S83.6', 'Tizza bog‘lamlarining cho‘zilishi', 'Растяжение связок коленного сустава', 'Jarohatlar va zaharlanishlar'),
  ('S93.4', 'Oyoq panjasi bog‘lamlarining cho‘zilishi', 'Растяжение связок голеностопного сустава', 'Jarohatlar va zaharlanishlar'),
  ('T14.0', 'Yuzaki shikastlanish, joyi aniqlanmagan', 'Поверхностная травма неуточнённой области тела', 'Jarohatlar va zaharlanishlar'),
  ('T14.1', 'Ochiq yara, joyi aniqlanmagan', 'Открытая рана неуточнённой области тела', 'Jarohatlar va zaharlanishlar'),
  ('T30.0', 'Kuyish, darajasi aniqlanmagan', 'Термический ожог неуточнённой степени', 'Jarohatlar va zaharlanishlar'),
  ('T63.4', 'Hasharot chaqishi zahari', 'Яд других членистоногих', 'Jarohatlar va zaharlanishlar'),
  ('T78.0', 'Ovqatdan anafilaktik shok', 'Анафилактический шок, вызванный пищей', 'Jarohatlar va zaharlanishlar'),
  ('T78.3', 'Angionevrotik shish (Kvinke)', 'Ангионевротический отёк', 'Jarohatlar va zaharlanishlar'),
  ('T78.4', 'Allergiya, aniqlanmagan', 'Аллергия неуточнённая', 'Jarohatlar va zaharlanishlar'),
  ('T88.7', 'Dorining nojo‘ya ta’siri', 'Патологическая реакция на лекарственное средство', 'Jarohatlar va zaharlanishlar'),
  ('Z00.0', 'Umumiy tibbiy ko‘rik', 'Общий медицинский осмотр', 'Profilaktika va ko‘riklar'),
  ('Z01.0', 'Ko‘z va ko‘rishni tekshirish', 'Обследование глаз и зрения', 'Profilaktika va ko‘riklar'),
  ('Z01.1', 'Quloq va eshitishni tekshirish', 'Обследование ушей и слуха', 'Profilaktika va ko‘riklar'),
  ('Z01.4', 'Ginekologik ko‘rik', 'Гинекологическое обследование', 'Profilaktika va ko‘riklar'),
  ('Z01.6', 'Rentgenologik tekshiruv', 'Радиологическое обследование', 'Profilaktika va ko‘riklar'),
  ('Z02.0', 'O‘quv muassasasiga kirish uchun ko‘rik', 'Обследование для поступления в учебное заведение', 'Profilaktika va ko‘riklar'),
  ('Z02.1', 'Ishga kirish uchun tibbiy ko‘rik', 'Предварительный медицинский осмотр при приёме на работу', 'Profilaktika va ko‘riklar'),
  ('Z02.7', 'Tibbiy ma’lumotnoma berish', 'Выдача медицинского свидетельства', 'Profilaktika va ko‘riklar'),
  ('Z03.9', 'Kuzatuv, tashxis tasdiqlanmagan', 'Наблюдение при подозрении на заболевание неуточнённое', 'Profilaktika va ko‘riklar'),
  ('Z09.9', 'Davolangandan keyingi kuzatuv', 'Обследование после лечения неуточнённого состояния', 'Profilaktika va ko‘riklar'),
  ('Z11.3', 'Jinsiy yo‘l bilan yuqadigan infeksiyalarga tekshiruv', 'Специальное скрининговое обследование на инфекции, передающиеся половым путём', 'Profilaktika va ko‘riklar'),
  ('Z12.4', 'Bachadon bo‘yni skriningi', 'Специальное скрининговое обследование шейки матки', 'Profilaktika va ko‘riklar'),
  ('Z13.1', 'Qandli diabetga skrining', 'Специальное скрининговое обследование на сахарный диабет', 'Profilaktika va ko‘riklar'),
  ('Z30.0', 'Kontratseptsiya bo‘yicha maslahat', 'Общие советы и консультации по контрацепции', 'Profilaktika va ko‘riklar'),
  ('Z30.1', 'Ichki vosita (spiral) qo‘yish', 'Введение внутриматочного противозачаточного средства', 'Profilaktika va ko‘riklar'),
  ('Z48.0', 'Jarrohlik chokini olish va bog‘lam', 'Уход за хирургическими повязками и швами', 'Profilaktika va ko‘riklar'),
  ('Z51.4', 'Davolashdan oldingi tayyorgarlik', 'Подготовительные процедуры для последующего лечения', 'Profilaktika va ko‘riklar'),
  ('Z71.3', 'Ovqatlanish bo‘yicha maslahat', 'Консультирование и наблюдение по вопросам диеты', 'Profilaktika va ko‘riklar'),
  ('Z76.0', 'Retsept yozdirish uchun murojaat', 'Выписка повторного рецепта', 'Profilaktika va ko‘riklar');

-- Nom bo'yicha qidiruv: `LIKE '%...%'` indeksdan foydalana olmaydi, lekin
-- jadval kichik (345 qator) va to'liq skan ham tez. Kod
-- bo'yicha prefiks qidiruvi esa birlamchi kalitdan foydalanadi.
CREATE INDEX IF NOT EXISTS "ICD10Code_category_idx" ON "ICD10Code"("category");
